{"name": "test_loginFailMethod", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <AppiumFramwork.tests.LoginTest.LoginTest testMethod=test_loginFailMethod>\n\n    @pytest.mark.run(order=3)\n    def test_loginFailMethod(self):\n        cl.allureLogs(\"App Opened\")\n        self.gt.clickLoginBotton()\n        self.gt.enterEmail()\n        self.gt.enterPassword2()\n        self.gt.clickOnLoginB()\n>       self.gt.verifyAdminScreen()\n\nLoginTest.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <AppiumFramwork.pages.LoginPage.LoginPageTest object at 0x00000205898FE4F0>\n\n    def verifyAdminScreen(self):\n        adminScreen = self.isDisplayed(self._pageTitle,\"text\")\n>       assert adminScreen == True\nE       AssertionError\n\n..\\pages\\LoginPage.py:44: AssertionError"}, "steps": [{"name": "App Opened", "status": "passed", "start": 1653640652693, "stop": 1653640652693}, {"name": "Click on Login Button", "status": "passed", "start": 1653640653455, "stop": 1653640653455}, {"name": "Entered email id", "status": "passed", "start": 1653640655181, "stop": 1653640655181}, {"name": "Entered Password", "status": "passed", "start": 1653640656335, "stop": 1653640656335}, {"name": "Clicked on Login Button in Login Screen", "status": "passed", "start": 1653640656910, "stop": 1653640656910}], "attachments": [{"name": "text", "source": "d5226367-ae03-471c-8607-8b144eb52464-attachment.png", "type": "image/png"}, {"name": "text", "source": "f7df824e-f90f-44a6-a533-b2a69703e38d-attachment.png", "type": "image/png"}, {"name": "log", "source": "2b7f5542-839d-4ad9-86ae-66005df102f8-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "71569a86-7c4d-4fe5-a3e8-81d79e8a6d6d-attachment.txt", "type": "text/plain"}], "start": 1653640652693, "stop": 1653640683613, "uuid": "77e79358-2a26-40f0-963d-0fa88c59effc", "historyId": "aeb6c84858cb897d59574054d46d09e3", "testCaseId": "1512c76b4b2d60f059541c0f73c45353", "fullName": "TestSuite.LoginTest#test_loginFailMethod", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "suite", "value": "TestSuite"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "BTZVBK3"}, {"name": "thread", "value": "7708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestSuite"}]}