{"name": "test_loginFailMethod", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <AppiumFramwork.tests.LoginTest.LoginTest testMethod=test_loginFailMethod>\n\n    @pytest.mark.run(order=3)\n    def test_loginFailMethod(self):\n        cl.allureLogs(\"App Opened\")\n        self.gt.clickLoginBotton()\n        self.gt.enterEmail()\n        self.gt.enterPassword2()\n        self.gt.clickOnLoginB()\n>       self.gt.verifyAdminScreen()\n\nLoginTest.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <AppiumFramwork.pages.LoginPage.LoginPageTest object at 0x0000020F3BBDB610>\n\n    def verifyAdminScreen(self):\n        adminScreen = self.isDisplayed(self._pageTitle,\"text\")\n>       assert adminScreen == True\nE       AssertionError\n\n..\\pages\\LoginPage.py:44: AssertionError"}, "steps": [{"name": "App Opened", "status": "passed", "start": 1653634828962, "stop": 1653634828962}, {"name": "Click on Login Button", "status": "passed", "start": 1653634829625, "stop": 1653634829625}, {"name": "Entered email id", "status": "passed", "start": 1653634831144, "stop": 1653634831144}, {"name": "Entered Password", "status": "passed", "start": 1653634832212, "stop": 1653634832212}, {"name": "Clicked on Login Button in Login Screen", "status": "passed", "start": 1653634832756, "stop": 1653634832756}], "attachments": [{"name": "text", "source": "a2a7867e-0429-4d63-b0cc-f74f52619643-attachment.png", "type": "image/png"}, {"name": "text", "source": "324f04de-a314-4075-832e-578f439e61f8-attachment.png", "type": "image/png"}, {"name": "log", "source": "1c032861-3938-465b-89cd-727754058ade-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "345250f9-0454-4913-8556-34fc719b9e5c-attachment.txt", "type": "text/plain"}], "start": 1653634828961, "stop": 1653634858481, "uuid": "e791aede-411e-41f8-b735-bdaaa5c924f9", "historyId": "aeb6c84858cb897d59574054d46d09e3", "testCaseId": "1512c76b4b2d60f059541c0f73c45353", "fullName": "TestSuite.LoginTest#test_loginFailMethod", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "TestSuite"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "BTZVBK3"}, {"name": "thread", "value": "5196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestSuite"}]}