{"name": "test_loginFailMethod", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <AppiumFramwork.tests.LoginTest.LoginTest testMethod=test_loginFailMethod>\n\n    @pytest.mark.run(order=3)\n    def test_loginFailMethod(self):\n        cl.allureLogs(\"App Opened\")\n        self.gt.clickLoginBotton()\n        self.gt.enterEmail()\n        self.gt.enterPassword2()\n        self.gt.clickOnLoginB()\n>       self.gt.verifyAdminScreen()\n\nLoginTest.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <AppiumFramwork.pages.LoginPage.LoginPageTest object at 0x00000175DED1FB20>\n\n    def verifyAdminScreen(self):\n        adminScreen = self.isDisplayed(self._pageTitle,\"text\")\n>       assert adminScreen == True\nE       AssertionError\n\n..\\pages\\LoginPage.py:44: AssertionError"}, "steps": [{"name": "App Opened", "status": "passed", "start": 1653648136270, "stop": 1653648136270}, {"name": "Click on Login Button", "status": "passed", "start": 1653648136982, "stop": 1653648136982}, {"name": "Entered email id", "status": "passed", "start": 1653648138438, "stop": 1653648138439}, {"name": "Entered Password", "status": "passed", "start": 1653648139572, "stop": 1653648139573}, {"name": "Clicked on Login Button in Login Screen", "status": "passed", "start": 1653648140129, "stop": 1653648140129}], "attachments": [{"name": "text", "source": "295a7f62-f997-4202-8160-b59cde8f7766-attachment.png", "type": "image/png"}, {"name": "text", "source": "4305840d-73bc-4a6a-bb05-04f6db29ccf7-attachment.png", "type": "image/png"}, {"name": "log", "source": "482fe605-c176-46ee-a6df-0877f75c9e30-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "262a33c3-665d-4a59-81df-9aa53417d15f-attachment.txt", "type": "text/plain"}], "start": 1653648136269, "stop": 1653648166959, "uuid": "81cb4968-608e-499f-ac5f-00032b4f0fb9", "historyId": "aeb6c84858cb897d59574054d46d09e3", "testCaseId": "1512c76b4b2d60f059541c0f73c45353", "fullName": "TestSuite.LoginTest#test_loginFailMethod", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "TestSuite"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "BTZVBK3"}, {"name": "thread", "value": "12440-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestSuite"}]}