{"name": "test_loginFailMethod", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <AppiumFramwork.tests.LoginTest.LoginTest testMethod=test_loginFailMethod>\n\n    @pytest.mark.run(order=3)\n    def test_loginFailMethod(self):\n        cl.allureLogs(\"App Opened\")\n        self.gt.clickLoginBotton()\n        self.gt.enterEmail()\n        self.gt.enterPassword2()\n        self.gt.clickOnLoginB()\n>       self.gt.verifyAdminScreen()\n\nLoginTest.py:37: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <AppiumFramwork.pages.LoginPage.LoginPageTest object at 0x000001FB66FF0400>\n\n    def verifyAdminScreen(self):\n        adminScreen = self.isDisplayed(self._pageTitle,\"text\")\n>       assert adminScreen == True\nE       AssertionError\n\n..\\pages\\LoginPage.py:44: AssertionError"}, "steps": [{"name": "App Opened", "status": "passed", "start": 1653640939078, "stop": 1653640939078}, {"name": "Click on Login Button", "status": "passed", "start": 1653640939719, "stop": 1653640939719}, {"name": "Entered email id", "status": "passed", "start": 1653640941485, "stop": 1653640941485}, {"name": "Entered Password", "status": "passed", "start": 1653640942624, "stop": 1653640942624}, {"name": "Clicked on Login Button in Login Screen", "status": "passed", "start": 1653640943235, "stop": 1653640943235}], "attachments": [{"name": "text", "source": "a0a3157e-8846-4bac-8e3f-de5eecf1bd93-attachment.png", "type": "image/png"}, {"name": "text", "source": "121d4678-4bb1-414c-91a6-9a0c45fc374e-attachment.png", "type": "image/png"}, {"name": "log", "source": "ac8556e8-e3ac-4d15-91c2-5cdfeead8c4c-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "094d40fe-34fb-4897-9838-68dcec0ea0d8-attachment.txt", "type": "text/plain"}], "start": 1653640939078, "stop": 1653640969916, "uuid": "b4d2ebf6-6ebd-4df7-94da-eea8cf12fb74", "historyId": "aeb6c84858cb897d59574054d46d09e3", "testCaseId": "1512c76b4b2d60f059541c0f73c45353", "fullName": "TestSuite.LoginTest#test_loginFailMethod", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "TestSuite"}, {"name": "subSuite", "value": "LoginTest"}, {"name": "host", "value": "BTZVBK3"}, {"name": "thread", "value": "280-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestSuite"}]}